### ISSUE TITLE
ЛР1 - Примеры тестов для мобильного приложения gmail

### ISSUE THREAD

**Issue by maruvuina** [maruvuina/software-testing#1]
**Объект тестирования: мобильное приложение gmail**
**Участники команды: Дрозд, Примова, Семенова.**

**По природе приложения:**
1. Проверка работы приложения на разных моделях мобильных устройств.
2. Реакция сенсорного экрана на различные манипуляции пользователя.
3. Проверка появления уведомления о полученном сообщении в верхней панели.

**По принципу работы с приложением:**

_**Позитивное:**_
1.	Отправка письма необходимому получателю.
2.	Заполнение всех полей формы верными значениями. 
3.	Проверка работы функции восстановления пароля.

_**Негативное:**_
1.	Ввод некорректных данных.
2.	Повторная регистрация.
3.	Авторизация с неверным логином/паролем.

**По степени важности тестируемых функций:**

_**Дымовое:**_
1.	При нажатии на вновь полученное электронное письмо пользователь переходит к содержимому электронной почты.
2.	При нажатии кнопки «Создать» отображается рамка для создания письма.
3.	Все вложения, прикрепленные к письму, доступны для скачивания.
4.	Вновь полученное электронное письмо отображается, как выделенное в разделе «Входящие».

_**Критический путь:**_
1.	Пользователь может прикрепить файл в качестве вложения в электронное письмо.
2.	Письма, составленные, но не отправленные, остаются в черновом разделе.
3.	Проверить, что если электронное письмо отправлено без темы, генерируется всплывающее окно, предупреждающее пользователя об отсутствии строки темы. Также проверить, что, приняв всплывающее сообщение, пользователь может отправить электронное письмо.

_**Расширенное:**_
1.	Проверить, что получатели электронной почты в скрытой копии не видны пользователю.
2.	Проверить, что письмо можно отправлять и на не почтовые адреса.
3.	Проверить, что во вновь полученном электронном письме правильно отображается идентификатор электронной почты отправителя или его имя, тема и тело письма (обрезанные до одной строки).

**По объекту:**

_**Функциональные:**_
1.	При нажатии на только что полученное электронное письмо пользователь переходит к содержимому электронной почты.
2.	Все вложения прикреплены к электронному письму и доступны для загрузки.
3.	Проверить какое максимальное количество получателей электронной почты, можно ввести в разделах «Кому», «Копия» и «Скрытая копия».

_**Нефункциональные:**_
1.	Отправить сто тысяч писем одновременно.
2.	Отправить письмо 100 пользователям одновременно.
3.	В разделе «Вложения» прикрепить 100 файлов. 

**По целям и задачам**

_**Инсталляционные:**_
1.	Подсчитывается ли при установке количество свободного места на диске и выдается ли предупреждение если места недостаточно.
2.	Сохраняются ли пользовательские настройки при попытке загрузить новую версию/обновить старую версию.
3.	При попытке установить ранее установленную версию приложения система должна ее распознать и выдать корректное сообщение.

_**Графический интерфейс:**_
1.	Вновь полученное электронное письмо отображается, как выделенное, в разделе «Входящие».
2.	На экране внизу появляется кнопка отмены/сброса  отправки сообщения.
3.	Все письма, помеченные как прочитанные, не выделены.

_**Удобство использования:**_
1.	Содержимое электронной почты отображается правильно с желаемым форматированием.
2.	Проверить, что пользователь может форматировать почту, используя такие параметры редактора, как выбор font-family, font-size, bold-italic-underline и т. д.
3.	Проверить лимит содержания текста / изображений, которые могут быть введены и успешно отправлены как содержимое письма.

_**Локализация:**_
1.	Корректные размеры кнопок и выпадающих списков.
2.	Название одного и того же элемента управления должно быть унифицированы для всего приложения и для всех составляющих его частей.
3.	Изменение часового пояса корректно обрабатывается для gmail.
4.	Корректные переносы в элементах управления.

_**Интернационализация:**_
1.	При переходе на другую локаль символы отображаются корректно.
2.	Проверка корректного формата даты при смене локали.
3.	Возможность изменения направления текста и его зеркалирование.

_**Безопасность:**_
1.	В случае неправильных учетных данных пользователя отображается сообщение типа «неверное имя пользователя или пароль» вместо точного сообщения, указывающего на поле, которое является неправильным. Так как сообщение "неправильное имя пользователя" поможет хакеру взломать поля одно за другим.
2.	Пользователь не может войти с неверным именем пользователя и паролем.
3.	Вложения проверяются на наличие вирусов перед загрузкой.

_**Совместимость:**_
1.	Стандартная установка Gmail на ОС Android.
2.	Стандартная установка Gmail на ОС iOS. 
3.	Отправка письма на не-gmail emailId, например на Yahoo.

_**Производительность:**_
1.	Проверить время ожидания сеанса входа.
2.	Проверить время отправки сообщения.
3.	Проверить лимит содержания текста, который может быть введен.

**Comment by vliplianina** [comment]
Принято
