### ISSUE TITLE
ЛР2 - Тестирование требований. Оповещения для клиента. Межбанковский перевод.

### ISSUE THREAD

**Issue by maruvuina** [maruvuina/software-testing#2]
**Участники команды: Дрозд, Примова, Семенова.**

--------------------------------------------------------------------------------------------------------------
**Оповещения для клиента.** 
Клиенту могут быть отправлены оповещения, используя Email, SMS или Push. Отправка SMS сообщений производится через внешний SMS-шлюз. Отправка email-сообщений производится через почтовый сервер Банка. Клиент может выбрать, на какой адрес отправить сообщение: заданный в его Профиле или на произвольный адрес. Необходимо предусмотреть доставки SMS-сообщений через другие системы коммуникаций (Viber, WhatsApp, и т.п.)

--------------------------------------------------------------------------------------------------------------

**Оповещения для клиента**

_Реализация отправки оповещений клиенту с помощью:_
-	Email
-	SMS
-	Push

_Отправка сообщений производится:_
-	либо через почтовый сервер Банка, если это email-сообщение
-	либо через SMS-шлюз, если это SMS-сообщение

_Клиент может выбрать, на какой адрес отправить сообщение:_ 
-	либо заданный в его Профиле 
-	либо на произвольный адрес

_Реализации доставка SMS-сообщений через:_
-	Viber
-	WhatsApp
-	Telegram
-	Facebook Messenger

--------------------------------------------------------------------------------------------------------------
**Межбанковский перевод** – возможность осуществления перевода денежных средств через расчетную сеть Банка России, а также через систему Swift. При этом должны быть реализованы все доступные на момент внедрения системы справочники (ОКАТО, БИК, КБК и др.), а также настройка уведомления клиента о выполнении Банком поручения (получено подтверждение от РКЦ об успешности обработки). Дополнительно необходимо реализовать возможность направления на e-mail получателя PDF-образа платежного документа с отметками Банка об исполнении. В случае оплаты налогов и штрафов необходимо реализовать максимально наглядный интерфейс по заполнению всех необходимых полей на основе полученного от ФНС / ГИБДД уведомления / постановления.

--------------------------------------------------------------------------------------------------------------

**Межбанковский перевод**
**_1)	осуществить перевод денежных средств с помощью:_**
-	расчетная сеть Банка России
-	система Swift

**_2)	Реализовать такие компоненты, как:_**
_1.	 справочники:_
-	ОКАТО
-	БИК
-	КБК

_2.	настройка уведомления клиента о выполнении Банком поручения:_
-	получения подтверждения от РКЦ об успешности обработки
-	получение подтверждения от РКЦ об ошибке обработки

_3. возможность направления на e-mail получателя PDF-образа платежного документа с отметками Банка об исполнении._

_4. максимально наглядный интерфейс для оплаты налогов и штрафов по заполнению всех необходимых полей на основе полученного от:_
-	ФНС уведомления
-	ФНС постановления
-	ГИБДД уведомления
-	ГИБДД постановления

**Comment by vliplianina** [comment]
Результаты тестирования должны быть предоставлены в виде запросов на уточнение требований. Формат оформления есть в презентации по лекции 2.

**Comment by maruvuina** [comment]
https://drive.google.com/open?id=1x2lBN6BYImgxkDSv_4q28pqQdNTgFEQ0VBggNvvspFg

**Comment by vliplianina** [comment]
Принято
